[tool.poetry]
name = "vbc"
version = "0.1.0"
description = ""
authors = []

[tool.poetry.dependencies]
python = "3.8"
numpy = "^1.21.4"
matplotlib = "^3.5.0"
scipy = "^1.7.3"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
